alert(16-6);
var a = 15;
var b = 5;
alert(a-b +" вывод с a-b");
var a1 = 15;
var b1 = 24;
var d = 0;
d = b1-a1 +1;
document.writeln(d + " Вывод через Writeln");
console.log(10);
document.getElementById("vivod").innerHTML = a1 - b + " Вывод через id";